### ISSUE TITLE
parse *.capnp error , import dlang.capnp error. Ask for help。

### ISSUE THREAD

**Issue by jasonsalex** [capnproto/capnproto-dlang#1]
create kiss-rpc.capnp file for dlang， error info, is not parse dlang.capnp:
/root/desktop/kiss-rpc.capnp:3:21-101: error: Import failed: /root/desktop/capnproto-dlang-master/compiler/src/main/schema/capnp/dlang.capnp

/root/desktop/kiss-rpc.capnp:5:2-7: error: Not defined: Dlang

dlang.capnp setting:
    @0xc5f2af96651f70ea;
     annotation module @0x9ee5c8f803b3b596 (file) : Text;

build make files, kiss-rpc.capnp:
     @0x9450b526a9ec41c6;
     
      using Dlang = import"/root/desktop/capnproto-dlang-master/compiler/src/main/schema/capnp/dlang.capnp";

     $Dlang.module("kiss-rpc");

**Comment by ThomasBrixLarsen** [comment]
The path has to be relative to your installation of capnproto.

If you install dlang.capnp to /usr/include/capnp it will work.

Alternatively you can do something like this: import "../../../../../../root/desktop/capnproto-dlang-master/compiler/src/main/schema/capnp/dlang.capnp";

**Comment by jasonsalex** [comment]
thank you , build is ok！：）

**Comment by ThomasBrixLarsen** [comment]
Great! Closing issue.
