### ISSUE TITLE
Compilation error with DMD64 D Compiler v2.067.1

### ISSUE THREAD

**Issue by Poyeyo** [capnproto/capnproto-dlang#2]
Performing "debug" build using dmd for x86_64.
capnproto-dlang 0.1.2: building configuration "lib"...
../../../.dub/packages/capnproto-dlang-0.1.2/capnproto-dlang/source/capnproto/DecodeException.d(28,8): Error: @nogc function 'capnproto.DecodeException.DecodeException.this' cannot call non-@nogc function 'object.Exception.this'
../../../.dub/packages/capnproto-dlang-0.1.2/capnproto-dlang/source/capnproto/PackedOutputStream.d(70,11): Error: module meta is in file 'std/meta.d' which cannot be read
import path[0] = ../../../.dub/packages/capnproto-dlang-0.1.2/capnproto-dlang/source/
import path[1] = /usr/include/dmd/phobos
import path[2] = /usr/include/dmd/druntime/import
dmd failed with exit code 1.

**Comment by ThomasBrixLarsen** [comment]
That version of dmd is ancient. I have no intentions of supporting it.

**Comment by Poyeyo** [comment]
Acknowledged.
