### ISSUE TITLE
Syntax sugar

### ISSUE THREAD

**Issue by trikko** [capnproto/capnproto-dlang#5]
Why doesn't it generate something like:

```D
obj.name = "hello"
obj.sub.name = "hello"
```

instead of:

```D
obj.setName("hello")
obj.getSub().setName("hello")
```

And

```D
people[0] 
```

instead of :

```D
people.get(0)
```
?

**Comment by ThomasBrixLarsen** [comment]
It might in the future.

opIndex is already supported for lists.

**Comment by kookman** [comment]
I've prepared a PR which addresses this. You can see the changes in my fork. Are you interested in a PR?

**Comment by kookman** [comment]
@trikko you could try this now and see what you think.

**Comment by trikko** [comment]
Sounds good! :+1:

**Comment by timotheecour** [comment]
FWIW, https://github.com/msoucy/dproto (protobuf in D) does that syntax sugar and it makes it much more usable

**Comment by ThomasBrixLarsen** [comment]
I forgot to close this half a year ago.
